# Generated by Django 5.2 on 2025-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_address1_useraddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_link_used',
            field=models.BooleanField(default=False),
        ),
    ]
