# Generated by Django 5.2 on 2025-05-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_reset_link_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reset_link_used',
        ),
    ]
